server:
  port: 8080

spring:
  application:
    name: NoExit
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB\
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
#    gmail smtp서버는 587포트 사용
    port: 587
    username: psh7492@gmail.com
    password: jvdd poxa ikuk ubya
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#            클라이언트와 서버간의 연결 대기시간/응답 대기시간/ 작업을 완료하는데 걸리는 시간
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
#          이메일 인증 코드의 만료시간 (30 * 60 * 1000 : 30분)
      auth-code-expiration-millis: 1800000